name: Check

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - dev-*

jobs:
  trial:
    name: Trial
    runs-on: ubuntu-latest
    env:
      ENV_1: ${{ secrets.ENV_1 }}

    steps:
      - uses: actions/checkout@v2

      - name: Test1
        env:
          ENV_2: ${{ secrets.ENV_2 }}
        run: |
          echo "Test1 - ENV1 = $ENV_1" >> result.txt
          echo "Test1 - ENV2 = $ENV_2" >> result.txt

      - name: Test2
        run: |
          echo "Test2 - ENV2 = $ENV_2" >> result.txt
        env:
          ENV_2: ${{ secrets.ENV_2 }}

      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Result
          path: result.txt
